name: test release

on:
  workflow_dispatch:

jobs:
  test_release:
    name: test release
    runs-on: ubuntu-latest
    steps:
    - name: file_test
      run : |
        mkdir ./测试
        echo 测试 >./测试/测试.txt
    - name: upload test
      uses: actions/upload-artifact@v4
      with:
        name: 测试
        path: ./测试
    - name: release test
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./测试
        tag: TEST
